### ISSUE TITLE
Typescript typings need to be properly reviewed and exported

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/itmat-broker#398]
Right now it is not possible to rely on typescript to guarantee proper type checking.
This is because types are in-line declared in functions.
https://github.com/dsi-icl/itmat-broker/blob/889d2ef5f4e8e9130eada7bbee7affb26835bb08/packages/itmat-interface/src/graphql/resolvers/studyResolvers.ts#L191
Moreover, there shouldn't be any location where "any" is used.

We also need to make sure types and interface exports are done consistently.

**Comment by sou-chon** [comment]
example given is resolver parameters specific
