### ISSUE TITLE
Bug of admintab in datasets.

### ISSUE THREAD

**Issue by wsy19961129** [dsi-icl/itmat-broker#581]
Is it a bug here, as AdminTabContect should have accept a parameter studyID?

https://github.com/dsi-icl/itmat-broker/blob/c81c1f21de322176559a0df0dd7ec7a27dd38dc3/packages/itmat-ui-react/src/components/datasetDetail/tabContent/admin/adminTab.tsx#L9-L10

https://github.com/dsi-icl/itmat-broker/blob/c81c1f21de322176559a0df0dd7ec7a27dd38dc3/packages/itmat-ui-react/src/components/datasetDetail/index.tsx#L37

**Comment by fguitton** [comment]
@wsy19961129 I don't understand what you mean ? It does have a `studyId` prop which it already uses.

**Comment by sou-chon** [comment]
i think it receives { match: params: { studyId: xxxx }}} instead of { studyId: xxx }

**Comment by wsy19961129** [comment]
Because when I try to access the "ADMINISTRATION" page under "Datasets", it returns "getStudy" undefined. Thus I am not certain if it is because of the following code:
https://github.com/dsi-icl/itmat-broker/blob/486e3029ad21cd9826c9d5dc95558f5b82787882/packages/itmat-ui-react/src/components/datasetDetail/index.tsx#L33-L38

When calling 'AdminTabContent', there misses the parameter 'studyId', thus in this component:
https://github.com/dsi-icl/itmat-broker/blob/486e3029ad21cd9826c9d5dc95558f5b82787882/packages/itmat-ui-react/src/components/datasetDetail/tabContent/admin/adminTab.tsx#L9-L11

it can not read data from 'getStudy'.

**Comment by sou-chon** [comment]
let me fix that in a bit

**Comment by sou-chon** [comment]
@wsy19961129 

Hi Siyao, Could you help me verify the following fix is good?
#585

**Comment by wsy19961129** [comment]
> @wsy19961129
> 
> Hi Siyao, Could you help me verify the following fix is good?
> #585

Sure, it works well on my machine!

**Comment by sou-chon** [comment]
@wsy19961129 cool if the fix is good please approve the PR then we can merge ;)
